### ISSUE TITLE
Make a new folder App Development and add AppDevelopment.md file

### ISSUE THREAD

**Issue by Radhey644** [Iliveinbianries/BitsBytesWrites#15]
i have already worked for you and I believe you liked it I would like to show you more of what i got so pls allow me to give you with one more file under hacktoberfest.

**Comment by Radhey644** [comment]
@Iliveinbianries pls review it once

**Comment by Radhey644** [comment]
Sir,
I have commited my work.
you can review it and pls specify that if any changes are there u want.

**Comment by Iliveinbianries** [comment]
I did not receive your PR.
Please check and verify.
