### ISSUE TITLE
Create a file at path Web/HowToLearnJS.md

### ISSUE THREAD

**Issue by chauhansumitdev** [Iliveinbianries/BitsBytesWrites#20]
Instructions:
Open folder Web
Inside that folder make a file Web/HowToLearnJS.md
Write content for it.

**Comment by MeenuyD** [comment]
Hello @chauhansumitdev I would like to work on this issue can you please assign it to me.

**Comment by harmit17** [comment]
@Iliveinbianries Can you assign this task to me?

**Comment by Iliveinbianries** [comment]
@harmit17 assigned to you ✅.
@MeenuyD already has an issue assigned therefor you can go with this.

**Comment by harmit17** [comment]
I have created a Pull request, you can review it.
