### ISSUE TITLE
Create a file at path General/WhatIsMultithreading.md

### ISSUE THREAD

**Issue by Iliveinbianries** [Iliveinbianries/BitsBytesWrites#29]
Instructions:
Open folder General
Inside that folder make a file Web/WhatIsMultithreading.md
Write content for it.

**Comment by HamnaJabbar** [comment]
Hi @Iliveinbianries ! Could you plz assign this issue to me?

**Comment by HamnaJabbar** [comment]
Hi @Iliveinbianries ! I have done with task and PR.
have a look. Thankyou.
