### ISSUE TITLE
Make a new folder AI and add WhatIsAI.md file

### ISSUE THREAD

**Issue by Iliveinbianries** [Iliveinbianries/BitsBytesWrites#3]
Follow the steps:
- Make a new folder AI
-  Create new file in AI/WhatIsAI.md
- Write the content for this file.

**Comment by nehareddies** [comment]
Hello, 
I am willing to work on this!

**Comment by nehareddies** [comment]
I have done this task!

**Comment by Iliveinbianries** [comment]
✅
