### ISSUE TITLE
Create a file General/OperatingSystem.md

### ISSUE THREAD

**Issue by Iliveinbianries** [Iliveinbianries/BitsBytesWrites#31]
Instructions:
Open folder General
Inside that folder make a file General/OperatingSystem.md
Write content for it

**Comment by HamnaJabbar** [comment]
Hi @Iliveinbianries !Could you plz assign this issue to me? and plz add hacktoberfest label. Thankyou

**Comment by HamnaJabbar** [comment]
Hi @Iliveinbianries !I have done the task and pr.
