### ISSUE TITLE
Create file at General/DBMS.md

### ISSUE THREAD

**Issue by Iliveinbianries** [Iliveinbianries/BitsBytesWrites#35]
Instructions:
Open folder General
Inside that folder make a file General/DBMS.md
Write content for it

**Comment by rishirajm007** [comment]
Hey @Iliveinbianries 
I am eager to make a contribution to this, and I respectfully request that you assign me this issue.

**Comment by MeenuyD** [comment]
Hello @Iliveinbianries I would like to work on this issue can you please assign it to me

**Comment by AshaHolla** [comment]
I would like to contribute as well. Pls assign thanks

**Comment by rishirajm007** [comment]
Hello, @Iliveinbianries ,
I would like to kindly remind you that I made the initial request for this issue. Therefore, I respectfully request that you assign it to me. 
Thank you for your consideration.

**Comment by Iliveinbianries** [comment]
Nothing to worry @rishirajm007 :) just allowing new contributors to collaborate as well, will soon be opening more issues to work on, you having experience with this repo are always welcome to open up more of more issues and work on them independently. Therefore I would suggest you to open more issues and work on them, learn more here : https://youtu.be/Ht7ml2fpF4M
Have a great day! :)

**Comment by rishirajm007** [comment]
Thank you for your understanding and the opportunity to contribute further, @Iliveinbianries. I appreciate your guidance and will certainly consider opening up more issues and working on them independently. I look forward to continued collaboration. Have a wonderful day! :)

**Comment by AshaHolla** [comment]
Pls review this PR @Iliveinbianries
