### ISSUE TITLE
Create a file at General/DiscreteMathematics.md

### ISSUE THREAD

**Issue by Iliveinbianries** [Iliveinbianries/BitsBytesWrites#37]
Instructions:
Open folder General
Inside that folder make a file General/DiscreteMathematics.md
Write content for it

**Comment by HamnaJabbar** [comment]
Hi @Iliveinbianries !Could you plz assign this to me?

**Comment by Jalaj028** [comment]
Hey @Iliveinbianries , I would like to work on this, can you please assign it to me?

**Comment by Jalaj028** [comment]
Hey @Iliveinbianries  I have created a pr, please let me know if I missed out on something.
