### ISSUE TITLE
Create file at ProgrammingLanguages/java/HowToLearnJava.md

### ISSUE THREAD

**Issue by Iliveinbianries** [Iliveinbianries/BitsBytesWrites#38]
Instructions:
Open folder ProgrammingLanguages
Inside that folder make a file ProgrammingLanguages/java/HowToLearnJava.md
Write content for it

**Comment by starliterss** [comment]
Hello @Iliveinbianries ,
I kindly request that you assign me the following issue under Hacktoberfest.

**Comment by Kola-Prabhas** [comment]
Could you please assign this to me?
