### ISSUE TITLE
Make a new folder Blockchain and add WhatIsBlockchain.md file

### ISSUE THREAD

**Issue by Iliveinbianries** [Iliveinbianries/BitsBytesWrites#4]
Follow the steps:

Make a new folder Blockchain
Create new file in AI/WhatIsBlockchain.md
Write the content for this file.

**Comment by MeenuyD** [comment]
Hello @Iliveinbianries I would like to work on this issue can you please assign it to me.

**Comment by Iliveinbianries** [comment]
Assigned to you ✅.
