### ISSUE TITLE
Write content for `Web/WhatIsNodeJS.md`

### ISSUE THREAD

**Issue by chauhansumitdev** [Iliveinbianries/BitsBytesWrites#53]
Instructions:
Open folder `Web`
Inside that folder make a file `Web/WhatIsNodeJS.md`
Write content for it

**Comment by MeenuyD** [comment]
Hello @Iliveinbianries I would like to work on this issue can you please assign it to me

**Comment by Iliveinbianries** [comment]
@sohamhaldar @MeenuyD  whoever submits the pr first will get it merged :)
